language: node_js
node_js:
- '0.10'
env:
  global:
  - GH_REF: github.com/chad-autry/hex-widget 
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
- npm run build:demo
after_success:
- chmod ugo+x ./deploy-gh-pages.sh
- ./deploy-gh-pages.sh
